---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  REDMINE_DB_POSTGRES: database
