---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pg-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pg-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-pg-app
    spec:
      initContainers:
      - image: busybox
        name: make-data-dir
        command: ["sh", "-c", "mkdir /data/pgdata"]
        volumeMounts:
        - name: pg-data
          mountPath: /data
      containers:
      - image: postgres:10.13
        name: postgres
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            value: testdatabase
          - name: POSTGRES_USER
            value: testuser
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: pg-pass
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: my-pvc
